title: "SciDash"
description: Rigorous, reproducible, extensible, data-driven model validation for science
google_analytics: UA-74220261-1
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
